[package]
name = "pms"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = "4"
dotenvy = "0.15"
sqlx = { version = "0.8", features = ["runtime-tokio", "macros", "mysql"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
